// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5li_pJnF67tmZOAtcB7aiFRb_3Kjp6io',
    appId: '1:400917952970:web:8160c5b2968527f1a0f733',
    messagingSenderId: '400917952970',
    projectId: 'oweflow-9cbfb',
    authDomain: 'oweflow-9cbfb.firebaseapp.com',
    storageBucket: 'oweflow-9cbfb.firebasestorage.app',
    measurementId: 'G-R9XTVC7EVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3Wf88uGSV6GNmEF38giNG4lagt5WWi4',
    appId: '1:400917952970:android:717b1417e8c17acea0f733',
    messagingSenderId: '400917952970',
    projectId: 'oweflow-9cbfb',
    storageBucket: 'oweflow-9cbfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNtMBN4twsk3nCr2yQ2PHiosQwrlIe6SE',
    appId: '1:400917952970:ios:6dfd951ae94b0bcfa0f733',
    messagingSenderId: '400917952970',
    projectId: 'oweflow-9cbfb',
    storageBucket: 'oweflow-9cbfb.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNtMBN4twsk3nCr2yQ2PHiosQwrlIe6SE',
    appId: '1:400917952970:ios:6dfd951ae94b0bcfa0f733',
    messagingSenderId: '400917952970',
    projectId: 'oweflow-9cbfb',
    storageBucket: 'oweflow-9cbfb.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5li_pJnF67tmZOAtcB7aiFRb_3Kjp6io',
    appId: '1:400917952970:web:117586b9f6165d52a0f733',
    messagingSenderId: '400917952970',
    projectId: 'oweflow-9cbfb',
    authDomain: 'oweflow-9cbfb.firebaseapp.com',
    storageBucket: 'oweflow-9cbfb.firebasestorage.app',
    measurementId: 'G-NYF7CF58LF',
  );

}